name: Publish Laravelapi
on: 
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: deploy-laravelapi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: deploy-laravelapi
      uses: SamKirkland/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: ${{ secrets.FTP_SERVER }}
